---
.add_ssh: &add_ssh |
  mkdir ~/.ssh
  echo $SSH_KEY > ~/.ssh/id_rsa
  chmod 600 ~/.ssh/id_rsa
  ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  
kind: pipeline
type: kubernetes
name: default

steps: 
- name: docker
  image: banzaicloud/drone-kaniko
  settings:
    email: louis.epsi.perdereau@gmail.com
    dockerfile: ./Dockerfile
    registry: docker.pkg.github.com
    repo: lperdereau/file-parser-hasura/api
    username:
      from_secret: github_username
    password:
      from_secret: github_token
  when:
    branch:
    - master
    event: push